{"name":"Verify_that_the_System_generates_an_error_mesasge_where_the_customer_has_provided_an_Invalid_amount_as_the_Transfer_Amount","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"java.lang.NullPointerException","trace":"java.lang.NullPointerException\r\n\tat USSD.C_Fund_Transfer_Account_to_Mobile_Money.Verify_that_the_System_generates_an_error_mesasge_where_the_customer_has_provided_an_Invalid_amount_as_the_Transfer_Amount(C_Fund_Transfer_Account_to_Mobile_Money.java:435)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)\r\n\tat java.lang.reflect.Method.invoke(Unknown Source)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)\r\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)\r\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\r\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.util.ArrayList.forEach(Unknown Source)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:764)\r\n\tat org.testng.TestRunner.run(TestRunner.java:585)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:384)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:286)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1140)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1069)\r\n\tat org.testng.TestNG.run(TestNG.java:1037)\r\n\tat org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)\r\n\tat org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)\r\n\tat org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)\r\n"},"stage":"finished","description":"Verify that the System generates an error mesasge where the customer has provided an Invalid amount as the Transfer Amount","steps":[],"attachments":[],"parameters":[],"start":1615189384327,"stop":1615189385924,"uuid":"5df76b8a-dfb5-4d6f-855f-64046149e180","historyId":"809468e78d22b0939fc3b827858a84f5","fullName":"USSD.C_Fund_Transfer_Account_to_Mobile_Money.Verify_that_the_System_generates_an_error_mesasge_where_the_customer_has_provided_an_Invalid_amount_as_the_Transfer_Amount","labels":[{"name":"package","value":"USSD.C_Fund_Transfer_Account_to_Mobile_Money"},{"name":"testClass","value":"USSD.C_Fund_Transfer_Account_to_Mobile_Money"},{"name":"testMethod","value":"Verify_that_the_System_generates_an_error_mesasge_where_the_customer_has_provided_an_Invalid_amount_as_the_Transfer_Amount"},{"name":"parentSuite","value":"Default suite"},{"name":"suite","value":"Default test"},{"name":"subSuite","value":"USSD.C_Fund_Transfer_Account_to_Mobile_Money"},{"name":"host","value":"TRUUGQA03"},{"name":"thread","value":"13980@TRUUGQA03.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"feature","value":"MOBILE MONEY"},{"name":"epic","value":"USSD FUND TRANSFERS"},{"name":"severity","value":"blocker"}],"links":[]}